### ISSUE TITLE
odroid_u3: misc: Change mac address on odroid-u3

### ISSUE THREAD

**Issue by gociii** [hexdump0815/linux-mainline-and-mali-on-odroid-u3#8]
In which file can I find the mac address stored please? (so I can change it)

**Comment by hexdump0815** [comment]
@gociii - it is defined in /boot/extlinux/extlinux.conf - you could either change the mac there or remove the mac option and then should get a new random mac address on each boot i think ... btw. new images based on v6.1 kernel coming soon ...

best wishes and good luck - hexdump

**Comment by hexdump0815** [comment]
i have now added a corresponding note to the odroid u3 readme
